require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LegalEntitiesController do

  # This should return the minimal set of attributes required to create a valid
  # LegalEntity. As you add validations to LegalEntity, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "org_name_full" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LegalEntitiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all legal_entities as @legal_entities" do
      legal_entity = LegalEntity.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:legal_entities)).to eq([legal_entity])
    end
  end

  describe "GET show" do
    it "assigns the requested legal_entity as @legal_entity" do
      legal_entity = LegalEntity.create! valid_attributes
      get :show, {:id => legal_entity.to_param}, valid_session
      expect(assigns(:legal_entity)).to eq(legal_entity)
    end
  end

  describe "GET new" do
    it "assigns a new legal_entity as @legal_entity" do
      get :new, {}, valid_session
      expect(assigns(:legal_entity)).to be_a_new(LegalEntity)
    end
  end

  describe "GET edit" do
    it "assigns the requested legal_entity as @legal_entity" do
      legal_entity = LegalEntity.create! valid_attributes
      get :edit, {:id => legal_entity.to_param}, valid_session
      expect(assigns(:legal_entity)).to eq(legal_entity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LegalEntity" do
        expect {
          post :create, {:legal_entity => valid_attributes}, valid_session
        }.to change(LegalEntity, :count).by(1)
      end

      it "assigns a newly created legal_entity as @legal_entity" do
        post :create, {:legal_entity => valid_attributes}, valid_session
        expect(assigns(:legal_entity)).to be_a(LegalEntity)
        expect(assigns(:legal_entity)).to be_persisted
      end

      it "redirects to the created legal_entity" do
        post :create, {:legal_entity => valid_attributes}, valid_session
        expect(response).to redirect_to(LegalEntity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved legal_entity as @legal_entity" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(LegalEntity).to receive(:save).and_return(false)
        post :create, {:legal_entity => { "org_name_full" => "invalid value" }}, valid_session
        expect(assigns(:legal_entity)).to be_a_new(LegalEntity)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(LegalEntity).to receive(:save).and_return(false)
        post :create, {:legal_entity => { "org_name_full" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested legal_entity" do
        legal_entity = LegalEntity.create! valid_attributes
        # Assuming there are no other legal_entities in the database, this
        # specifies that the LegalEntity created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(LegalEntity).to receive(:update).with({ "org_name_full" => "MyString" })
        put :update, {:id => legal_entity.to_param, :legal_entity => { "org_name_full" => "MyString" }}, valid_session
      end

      it "assigns the requested legal_entity as @legal_entity" do
        legal_entity = LegalEntity.create! valid_attributes
        put :update, {:id => legal_entity.to_param, :legal_entity => valid_attributes}, valid_session
        expect(assigns(:legal_entity)).to eq(legal_entity)
      end

      it "redirects to the legal_entity" do
        legal_entity = LegalEntity.create! valid_attributes
        put :update, {:id => legal_entity.to_param, :legal_entity => valid_attributes}, valid_session
        expect(response).to redirect_to(legal_entity)
      end
    end

    describe "with invalid params" do
      it "assigns the legal_entity as @legal_entity" do
        legal_entity = LegalEntity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(LegalEntity).to receive(:save).and_return(false)
        put :update, {:id => legal_entity.to_param, :legal_entity => { "org_name_full" => "invalid value" }}, valid_session
        expect(assigns(:legal_entity)).to eq(legal_entity)
      end

      it "re-renders the 'edit' template" do
        legal_entity = LegalEntity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(LegalEntity).to receive(:save).and_return(false)
        put :update, {:id => legal_entity.to_param, :legal_entity => { "org_name_full" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested legal_entity" do
      legal_entity = LegalEntity.create! valid_attributes
      expect {
        delete :destroy, {:id => legal_entity.to_param}, valid_session
      }.to change(LegalEntity, :count).by(-1)
    end

    it "redirects to the legal_entities list" do
      legal_entity = LegalEntity.create! valid_attributes
      delete :destroy, {:id => legal_entity.to_param}, valid_session
      expect(response).to redirect_to(legal_entities_url)
    end
  end

end
